version: "3.9"

services:
  db:
    image: 176386839925.dkr.ecr.eu-north-1.amazonaws.com/text2sql-db:latest

    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=text2sql
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_PORT=5433
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d text2sql"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - text2sql-network

  backend:
    image: 176386839925.dkr.ecr.eu-north-1.amazonaws.com/text2sql-backend:latest
    container_name: backend
    restart: always
    volumes:
      - static_volume:/app/staticfiles
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DJANGO_SETTINGS_MODULE=text2sql.production_settings
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - DATABASE_URL=postgres://admin:mypassword@db:5432/text2sql
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=text2sql
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=mypassword
      - SQL_SERVER_HOST=host.docker.internal
      - SQL_SERVER_TIMEOUT=60
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - text2sql-network
      - text2sql-net

  frontend:
    image: 176386839925.dkr.ecr.eu-north-1.amazonaws.com/text2sql-frontend:latest
    container_name: temp-text2sql-frontend
    restart: always
    ports:
      - "5172:5173"
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://host.docker.internal:8000
      - NODE_ENV=production
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - text2sql-network

networks:
  text2sql-network:
    driver: bridge
  text2sql-net:
    external: true

volumes:
  postgres_data:
    name: text2sql_postgres_data
  static_volume:
    external: true
